# TIER 0
# 1945-1955 "sounding rockets" : aerobee, A4/blossom-1/bumper, R1-5. RP-0 TL-1, early tech.

start:

# TIER 1
# 1950-1957 "going ballistic" : redstone. RP-0 TL0.

basicRocketry: # early rocket launchers, spin stablized solid kick motors. 1950-1957.
engineering101: # early construction
earlyAvionics: # early electro-mechanical flight controllers, 1953-1957.

# TIER 2
# 1957-~1960 "kanines in space" : vanguard/juno2/atlas/thor-able, pioneer1-5/vanguard/grab/transit, explorer, R-7, sputnik/luna2-3. RP-0 TL1.

generalRocketry: # basic orbital rocketry. 1958-1962
basicSolids: # first all-solid launchers, 1957-1960
basicConstruction: # larger tanks, 1958-1960
basicAvionics: # electro-mechanical flight controllers
survivability: # reentry-proof orbital probes, lunar impactors, 1959
stability: # gyrostabilization and RCS, 1959

# TIER 3
# 1960-~1966 "ground control to major kerman" : mercury/gemini/scout/centaur/titan3, surveyor/pioneer6-7/mariner, block E&L/vostok/voskhod/proton/molniya, polyot/luna 9-13. RP-0 TL2.

hydroloxTL2: # first hydrolox engines, 1962
advRocketry: # mature orbital rocketry, 1963
fuelSystems: # staged combustion, 1961
matureSolids: # larger solids with thrust vectoring, 1960-1963
generalConstruction: # larger tanks
flightControl: # early digital avionics, 1964
enhancedSurvivability: # basic capsules with orbital reentry, 1960-63. mercury/vostok
basicScience: # improved instrumentation, 1962
electrics: # antennae, fuel cells, high-efficiency batteries, foldable solar panels, 1964
miniaturization: # beyond LEO probes, science, scanners, 1964
landing: # soft landing on other bodies, 1964-67

# TIER 3.5
simpleCommandModules: # second-gen capsules, with EVAs, 1964. gemini/voskhod

# TIER 4
# 1967-1969 "the kraken has landed" : protonK/saturnV, apollo/LEM, pioneer9, soyuz7K-OK/zond7K-L1, RP-0 TL3 F-1, H-1 uprated, etc.

hydroloxTL3: # hydrolox engines, 1967
heavyRocketry: # heavy orbital rocketry, beyond LEO
propulsionSystems: # improved staged combustion
largeSolids: # large segmented solids
advConstruction: # improved tanks & lunar return heat shielding
commandModules: # advanced capsules with lunar reentry. apollo/soyuz7K-OK/zond7K-L1
spaceExploration: # crewed landers. LEM
advElectrics: # antennae, probes, late 1960s
advFlightControl: # RCS, docking, avionics
shortTermHabitation: # single mission designs with reentry vehicle attached.

# TIER 5
# 1970-1980 "islands in the sky" : bigGemini, pioneer10-11/voyager/skylab, N1, soyuz7K-T+TM+OKS+LOK/LK/kosmosTKS/FGB/ASTP/apas75, luna17, salyut1-6/almaz. RP-0 TL4.

hydroloxTL4: # mature hydrolox engines, 1970
heavierRocketry: # refined rocketry
precisionPropulsion: # advanced staged propulsion
advFuelSystems: # improved solids, improved thrust vectoring
specializedConstruction:
actuators:
#advLanding: # deprecated
specializedControl: # integrated circuit avionics, 1970s
advExploration: # lunar exploration (big gemini/luna17)
precisionEngineering: # probes, science, scanners
electronics: # microchips, early 1970s
largeElectrics: # antennae, batteries, larger solar panels, early 1970s
earlyStations: # first stations with crew rotations and resupply, early 1970s

# TIER 5.5

nuclearPropulsion:
largeVolumeContainment: # large segmented solids
advMetalWorks:
composites:
highAltitudeFlight:
heavyAerodynamics:
advActuators:
# heavyLanding: deprecated
# fieldScience: deprecated
heavyCommandModules:
scienceTech: # science, scanners
unmannedTech: # probes

# TIER 6
# 1980-1990 "reusable space program" : STS/nova, spacelab/salyut7, ius/magellan/tdrsA-G, energia/zenit/buran/mir, soyuz-T/progress7k-TG. RP-0 TL5.

hydroloxTL5: # closed-cycle hydrolox engines, 1980
veryHeavyRocketry: # advanced rocketry
stagedTL5: # mature staged combustion
highPerformanceFuelSystems: # high-performance solids
avionicsTL5: # routine docking
nanolathing:
metaMaterials:
experimentalActuators:
hypersonicFlight:
experimentalAerodynamics:
advMotors:
specializedCommandPods:
advScienceTech: # scanners, science
specializedScienceTech:
ionPropulsion:
advUnmannedTech: # probes
automation: # advanced electronics
specializedElectrics: # antennae, batteries
advSolarTechnology: # solar

# TIER 7
# 1990-2000 "deep space probes" : hubble/KISS/galileo/NEARshoemaker/deepspace1/ulysses, soyuz-TMA/fregat. RP-0 TL6, the first bits of EELV tech.

hydroloxTL6: # advanced hydrolox engines
experimentalRocketry: # refined rocketry
stagedTL6: # refined staged combustion
specializedFuelStorage: # refined solids
avionicsTL6: # orbital assembly avionics, 1990s
exoticAlloys:
offWorldRobotics:
aerospaceTech:
experimentalScience:
longTermScienceTech:
advIonPropulsion:
largeProbes: # probes
mechatronics:
experimentalElectrics: # science, scanners
advPhotovoltaicMaterials: # batteries
cuttingEdgeSolarTechnology: # solar

# TIER 8
# 2000-2010 "commercial resupply" : delta-2/atlas3-V, EOS/messenger/deepimpact/dawn/newhorizons, tiangong. RP-0 TL7, Modern day tech.

hydroloxTL7: # modern hydrolox engines
giganticRocketry: # modern rocketry
stagedTL7: # modern staged combustion
avonicsTL7: # modern avionics
exoticFuelStorage: # modern solids
orbitalAssembly:
advOffworldMining:
scientificOutposts:
plasmaPropulsion:
advancedGriddedThrusters:
artificialIntelligence:
highTechElectricalSystems:
microwavePowerTransmission:

# TIER 9
# 2010-2020 "back to the mun or bust" : orion/altair/ares, spaceY/antares/cygnus, angara/federation. RP-0 TL7.

colossalRocketry:
orbitalMegastructures:
resourceExploitation:
highEnergyScience:
advAlectromagneticSystems:
experimentalGriddedThrusters:
